version = project.portable_jukebox_version

addPolymerDependency()
dependencies {
	// the item models and lang, served in Polymer's resource pack
	implementation("eu.pb4:polymer-resource-pack:${project.polymer_version}")
}
addSGUIDependency()

dependencies {
	implementation("maven.modrinth:lithium:$lithium_version-fabric")
	compileOnly("maven.modrinth:ledger:$ledger_version")
}